config/routes.rb
Rails.application.routes.draw do
  resources :users

  # must be above dynamic recipes routes, otherwise it interprets
  # servings as an id
  get '/recipes/servings', to: 'recipes#servings', as: 'servings'

  get 'ratings/create'
  get 'comments/create'

  resources :recipes do
    resources :ratings
    resources :comments
  end

  resources :ingredients

  root 'users#welcome'
  get '/auth/:provider/callback' =>'sessions#create'
  get '/signin' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  post '/signin' => 'sessions#create'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :ratings
  has_many :commenting_users, through: :comments, source: :users
  has_many :rating_users, through: :ratings, source: :users
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :directions
  accepts_nested_attributes_for :directions
  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :ratings
  default_scope { order(title: :asc) }

  def self.servings
    unscope(:order).order(servings: :asc)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  PLACEHOLDER_DIRECTIONS = ['Pour', 'Mix', 'Drink']

  def show
    @recipe = Recipe.find_by(id: params[:id])
    @comment = @recipe.comments.build
    @rating = Rating.find_by(recipe_id: @recipe.id, user_id: current_user.id) || @recipe.ratings.build

    # gets rid of nil comments
    @valid_comments = @recipe.comments.select { |c| c.user }
     respond_to do |format|
      format.html { render :show }
      format.json { render json: @recipe }
    end
  end

  def new
    @recipe = Recipe.new
    @recipe.directions.build([
      {body: ''},
      {body: ''},
      {body: ''}])
    @pds = PLACEHOLDER_DIRECTIONS
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.save
      redirect_to user_path current_user
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
      @pds = PLACEHOLDER_DIRECTIONS
      render new_recipe_path
    end
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
    @pds = PLACEHOLDER_DIRECTIONS
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to user_path current_user
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
      @pds = PLACEHOLDER_DIRECTIONS
      render :edit
    end
  end

  def servings
    @recipes = Recipe.servings
  end

  private

    def recipe_params
      # two things are not cooperating:
      # 1/ my validation constraints do not allow empty strings
      # my model should *not* have an exclusion, it is not its concern
      # 2/ building an ingredient name text field is empty by default
      # to deal with this, I sanitize the ingredients_attributes hash
      # *prior* to it being passed as a param

      # also `dig` is hash method for pulling data from nested hashes :3
      # it is a safe navigation operator
      if params.dig(:recipe, :ingredients_attributes, "0", :name) == ""
        params[:recipe][:ingredients_attributes] = {}
      end
      params.require(:recipe).permit(:user_id,
        :title, :servings, :time, :description,
        ingredients_attributes: [:name],
        ingredient_ids: [],
        directions_attributes: [:id, :body]
      )
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
      prohibited kept this recipe from being saved:
    </h2>

    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<br>

<h2>What is it? // Info </h2>

<%= form_for @recipe do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.label :title, "Drink name:" %>
  <%= f.text_field :title, placeholder: "the naughtier the better ;)",
    class: 'form-control' %>

  <%= f.label :servings, "How many people we serving?" %>
  <%= f.number_field :servings, placeholder: "more than 6 is a party~",
    in: 1..100, class: 'form-control' %>

  <%= f.label :time, "Prep. time (in minutes):"  %>
  <%= f.number_field :time, class: 'form-control' %>

  <%= f.label :description, "Tell us a little bit about your masterpiece <3" %>
  <%= f.text_area :description, class: 'form-control' %>

  <h3>How do you make it? // Directions </h3>
  <%= f.fields_for :directions, @recipe.directions do |direction_fields| %>
     <%= direction_fields.label :direction, (direction_fields.index + 1).to_s + '/'  %>
     <%= direction_fields.text_field :body,
       placeholder: @pds[direction_fields.index],
       class: 'form-control' %>
   <% end %>

   <h3>What's in it? // Ingredients </h3>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all,
      :id, :name, prompt: true %>

   <h5>Or add your own:</h5>
   <%= f.fields_for :ingredients, @recipe.ingredients.build do |ff| %>
     <%= ff.text_field :name %>
   <% end %>

   <br>
  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/recipes/edit.html.erb
<%= render 'form', post: @recipe %>

app/views/recipes/new.html.erb
<h2>What is it? // Info </h2>

<%= form_for(@recipe) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.label :title, "Drink name:" %>
  <%= f.text_field :title, placeholder: "the naughtier the better ;)", class: 'form-control' %>

  <%= f.label :servings, "How many people we serving?" %>
  <%= f.number_field :servings, placeholder: "more than 6 is a party~", in: 1..100, class: 'form-control' %>

  <%= f.label :time, "Prep. time (in minutes):"  %>
  <%= f.number_field :time, class: 'form-control' %>

  <%= f.label :description, "Tell us a little bit about your masterpiece <3" %>
  <%= f.text_area :description, class: 'form-control' %>

  <h3>How do you make it? // Directions </h3>
  <%= f.fields_for :directions, @recipe.directions do |direction_fields| %>
     <%= direction_fields.label :direction, (direction_fields.index + 1).to_s + '/'  %>
     <%= direction_fields.text_field :body,
       placeholder: @pds[direction_fields.index],
       class: 'form-control' %>
   <% end %>

   <h3>What's in it? // Ingredients </h3>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name, prompt: true %>

   <h5>Or add your own:</h5>
   <%= f.fields_for :ingredients, @recipe.ingredients do |ingredients_fields| %>

      <%= ingredients_fields.text_field :name, placeholder: "lemon juice" %>
      <br>
   <% end %>


   <br>
  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/recipes/servings.html.erb
<% @recipes.each do |r| %>
    <%= link_to r.title, recipe_path(r) %><br>
    Servings: <%= r.servings %> by <%= r.user.email %><br>
    ------------------------------------------------<br>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %><br></h1>
Description: <%= @recipe.description %><br>
Prep time: <%= @recipe.time %> minutes<br>
<br>
Directions:
<ol>
  <% @recipe.directions.each do |d| %>
  <li><%= d.body %></li>
<% end %>
</ol>
<br>
Ingredients:
<% @recipe.ingredients.each do |i| %>
  <li><%= link_to i.name, ingredient_path(i) %></li>
<% end %>
<br>

<% if_logged_in?(login_link_text: "Log in to rate this recipe") do %>
  <% if current_user.id == @recipe.user_id %>
    <%= link_to "Edit Recipe", edit_recipe_path(@recipe.id) %>
  <% else %>

  <h4>Rate this recipe:</h4>
    <%= form_for [@recipe, @rating] do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.radio_button :star, 1 %>
      <%= f.label :star, '⭐' %>

      <%= f.radio_button :star, 2 %>
      <%= f.label :star, '⭐⭐' %>

      <%= f.radio_button :star, 3 %>
      <%= f.label :star, '⭐⭐⭐' %>

      <%= f.radio_button :star, 4  %>
      <%= f.label :star, '⭐⭐⭐⭐'%>

      <%= f.radio_button :star, 5 %>
      <%= f.label :star, '⭐⭐⭐⭐⭐' %>

      <%= f.submit "Rate", class: "btn btn-info" %>
    <% end %>

  <% end %>
<% end %>

<h4>Comments:</h4>
<% if current_user %>
Say something nice: <br>
  <%= form_for [@recipe, @comment] do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.text_area :content %>
    <%= f.submit "Comment", class: "btn btn-success" %>
  <% end %>
<% else %>
<br>
<%= link_to "Log in to say something nice", signin_url %>
<% end %>

<%= link_to "See all comments here", recipe_comments_path(@recipe), class: "load_comments" %>

<ul id="comments">
</ul>