config/routes.rb
Rails.application.routes.draw do
  resources :users

  # must be above dynamic recipes routes, otherwise it interprets
  # servings as an id
  get '/recipes/servings', to: 'recipes#servings', as: 'servings'

  get 'ratings/create'
  get 'comments/create'

  resources :recipes do
    resources :ratings
    resources :comments
  end

  resources :ingredients

  root 'users#welcome'
  get '/auth/:provider/callback' =>'sessions#create'
  get '/signin' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  post '/signin' => 'sessions#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hair of the Dog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-dark bg-dark navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">

        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <a class="navbar-brand" href="<%= servings_path %>"/>See all recipes</a>
        <% if current_user %>
          <a class="navbar-brand" href="<%= user_path current_user %>"/><%= current_user.email %>'s profile</a>
          <%= link_to "New cocktail", new_recipe_path, method: :get, class: "navbar-brand" %>
          <%= link_to "Log Out", logout_path, method: :get, class: "navbar-brand" %>
        <% else  %>
          <a class="navbar-brand" href="<%= new_user_url %>"/>Sign Up</a>
          <a class="navbar-brand" href="<%= signin_url %>"/>Log In</a>
        <% end  %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
          <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form> -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>